server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  data:
    mongodb:
        uri: mongodb+srv://rodo:nttdata@cluster0.zjvp3.mongodb.net/service-products?retryWrites=true&w=majority
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://${eureka.instance.hostname}:8761/eureka/